# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "DenunciaLaCorrupcion" do

pod 'AFNetworking', '~> 2.4'
pod 'SWRevealViewController', '~> 2.0.0'
pod 'BlurryModalSegue'

end

target "DenunciaLaCorrupcionTests" do

end

